name: Create and Publish Release

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tar.gz files
        run: |
          mkdir -p release-assets
          for dir in packages/*/; do
            dir_name=$(basename "$dir")
            tar -czvf "release-assets/${dir_name}-${VERSION}.tar.gz" -C "$dir" .
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-assets/*.tar.gz